FROM alpine:latest

ARG GPG_PUBLICKEY=backup-to-cloud_publickey.asc
ARG APP_LOCATION=/app

RUN apk --no-cache add \
  bash \
  curl \
  gnupg

# Create the /app directory
RUN mkdir $APP_LOCATION

# Set the working directory to $APP_LOCATION
WORKDIR $APP_LOCATION

# Copy the contents of the local /src folder to the current working directory ($APP_LOCATION) in the container
COPY /src .

# Import the GPG public key
RUN gpg --import $APP_LOCATION/$GPG_PUBLICKEY

CMD ["/bin/bash"]
