FROM alpine:latest

# Arguments
ARG APP_LOCATION=/app

# Install packages
RUN apk --no-cache add \
  bash \
  curl \
  gnupg

# Create the /app directory
RUN mkdir $APP_LOCATION

# Set the working directory to $APP_LOCATION
WORKDIR $APP_LOCATION

# Copy the contents to the current working directory
COPY /src .

# Set ownership
RUN chown -R 1000:2000 $APP_LOCATION

CMD ["/bin/bash"]
